### ISSUE TITLE
RHEL 7.5 Error: Failed dependencies

### ISSUE THREAD

**Issue by oleg-pahl** [alexander-naumov/pam-accesscontrol#1]
**[root@redhat tmp]# rpm -i pam-accesscontrol-0.94-2.1.noarch.rpm** 

error: Failed dependencies:

	/usr/bin/python3 is needed by pam-accesscontrol-0.94-2.1.noarch
	pam-python is needed by pam-accesscontrol-0.94-2.1.noarch
	python3-qt5 is needed by pam-accesscontrol-0.94-2.1.noarch

```
> FYI:
> Kernel: 3.10.0-862.el7.x86_64 GNU/Linux
```

**Comment by oleg-pahl** [comment]
There is no `pam-python` in EPEL repo. 
Please fix / use: `python-pam-0.1.4-1.el7.noarch.rpm`

**Comment by oleg-pahl** [comment]
First one I can fix with cmd:

[# yum install python34 python34-libs](https://centos.pkgs.org/7/epel-x86_64/python34-3.4.8-1.el7.x86_64.rpm.html)

FYI:
`python34.x86_64` : Version 3 of the Python programming language aka Python 3000
`python36.x86_64` : Interpreter of the Python programming language

**Comment by oleg-pahl** [comment]
The last dep issue fix with:

```
yum -y install https://rhel7.iuscommunity.org/ius-release.rpm
yum -y install python36u-pip
pip3.6 install pyqt5
```

**Comment by alexander-naumov** [comment]
Hi Oleg,
first of all, thanks for report. I'm happy to see, that someone find this project useful.

If I understand it correctly, there is no **pam-python** package available for RedHat/CentOS at the moment[1]. Please keep in mind, that **python-pam** is completely different project ;)

And yes, it seems that RedHat/CentOS users will need to install **pam_python.so** manually.
I can add **python34** as a dependency and your installing steps to the install section of spec file, so that users know next steps to get it works.

[1] https://gist.github.com/jorritfolmer/e4bfb69b6d609542730b

**Comment by alexander-naumov** [comment]
Good news. I rebuild pam-python for CentOS/RHEL systems!
Please test it: https://download.opensuse.org/repositories/home:/Alexander_Naumov:/DEV-pam-accesscontrol/

pam-python and pam-accesscontrol are in the same repo. This is DEV repo. If everything goes well, I will update main repo.
```
> cd /etc/yum.repos.d/
> wget https://download.opensuse.org/repositories/home:Alexander_Naumov:DEV-pam-accesscontrol/RHEL_7/home:Alexander_Naumov:DEV-pam-accesscontrol.repo
> yum install pam-accesscontrol
```
Please let me know if everything looks good ;-)

**Comment by alexander-naumov** [comment]
No reply for 12 days. Issue is closing as invalid.
